services:
  - type: web
    name: e-care-spring
    runtime: java
    buildCommand: mvn clean package
    startCommand: java -jar target/E-care-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/temurin-17-jdk-amd64
      - key: PORT
        value: 8080